import './globals.css'
import React from "react";
import NavBar from "@/app/components/NavBar";
import {createTheme, ThemeProvider} from "@mui/material";
import {grey} from "@mui/material/colors";
import {Metadata} from "next";

export const metadata: Metadata = {
    title: "sss's Portfolio",
    description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
